# -*- coding: utf-8 -*-
"""Hand_writing_recogonization_using_cnn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18K3zuXwfucIj2YLtg1_N1sUrcq6vf9PY
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import datasets,layers,models
import matplotlib.pyplot as plt

(x_train,y_train),(x_test,y_test) = datasets.mnist.load_data()

x_train, x_test = x_train / 255.0, x_test / 255.0

plt.imshow(x_train[20])

model = models.Sequential()
model.add(layers.Conv2D(32, (3,3), activation='relu', input_shape = (28,28,1)))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64, (3,3), activation='relu'))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64, (3,3), activation='relu'))

model.summary()

model.add(layers.Flatten())
model.add(layers.Dense(64,activation='relu'))
model.add(layers.Dense(10))

model.summary()



model.compile(optimizer='adam',
              loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics = ['accuracy'])

history = model.fit(x_train, y_train, validation_data=(x_test,y_test) ,epochs=15)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['training data', 'validation data'], loc = 'lower right')

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['training data', 'validation data'], loc = 'upper right')

import numpy as np
y_pred = model.predict(x_test)

pred=np.argmax(y_pred,axis=1)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,pred))

plt.imshow(x_test[2004],cmap='gray')
plt.title(f"y_test:{y_test[2004]},y_pred:{pred[2004]}")

tf.keras.models.save_model(model, 'model.hdf5')#hierachical data formate version 5

